# Build

[build]
  command = "npm run build"
  publish = "build"

[build.environment]
  NODE_VERSION = "20"

# Redirects

## pride-flags.netlify.app

[[redirects]]
  from = "https://pride-flags.netlify.app/*"
  to = "https://flag.is/:splat"
  status = 302
  force = true

## pride-flags.fynn.be

[[redirects]]
  from = "https://pride-flags.fynn.be/*"
  to = "https://flag.is/:splat"
  status = 302
  force = true

## Page redirects

[[redirects]]
	from = "/flags/*"
	to = "/:splat"
	status = 301

## 404

[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404
